### PR TITLE
edit spin Formula test procedure to verify installed version

### LINKED ISSUE #17: update spin Formula's test procedure
per notes in #13 and #15 , now that `brew install fermyon/tap/bart` resolved & working, I'll quickly update the spin Formula to use version-validation test style, like the bart Formula uses

### PR DESCRIPTION
**Pull request by dimitrilw**
Performs version validation after installation & closes #17 .

### CODE REVIEW

**Comment by dimitrilw** [comment]
ok... I swear I looked in my repo to confirm I'd signed the commit before making the PR...... :|

image

...not sure why DCO check failed, but following the bot's instructions & will resubmit PR. :|

**Review by kate-goldenring — COMMENTED** [review]
This is a great addition @dimitrilw! The test bot is quite picky. If the test loop is getting tiresome, i think the best command to test syntax locally is `brew test-bot --only-tap-syntax`

**Review by kate-goldenring — DISMISSED** [review]

**Review by kate-goldenring — CHANGES_REQUESTED** [review]
@dimitrilw can you remove the `steps_output.txt` file?

**Comment by dimitrilw** [comment]
@kate-goldenring , I apologize for being slow. I realize I will be docked 10 free-labor dollars on my monthly salary. 😂 

File `steps_output.txt` removed and `.gitignore` added so future contributors will not make the same error.

**Comment by dimitrilw** [comment]
I also just added a note to the Readme re running test-bot locally. I hope that out-of-scope addition is ok.

**Comment by kate-goldenring** [comment]
@dimitrilw thank you for updating the readme too. I found running that command locally not very helpful (despite recommending it). Did you find that you were able to specify it to test a specific, yet to be installed formula? 

We also need to rebase this off latest main again. Sorry! I realized that adding testing for version is another place someone could mismatch version so i made an update in this PR to use the version variable throughout the formula which this could leverage: https://github.com/fermyon/homebrew-tap/pull/21

**Comment by dimitrilw** [comment]
I'll rebase pronto.

Re local run: really no idea. I ran it. It didn't complain. Neither did the Cloud-CI run. Next time cloud run fails but local passes, then I can respond with "nope; no use." 😄  ...but until then, I will go with a healthy dose of faith that it does *something*, even if that "something" is just a placebo effect for me.

**Comment by dimitrilw** [comment]
Merge was not happy. Cleaner to push as new branch; please look to PR #22 . Apologies for the mess, @kate-goldenring . ....git. 🤷🏻

**Pull request closed without merging**
